### ISSUE TITLE
update checker needs update

### ISSUE THREAD

**Issue by VierEck** [nonperforming/openspadesplus#22]
so i tried out the newest release (revision 10) and upon startup the update checker tells me i have revision 9. 

i installed the windows build from here https://github.com/nonperforming/openspadesplus/releases/tag/rev-10

playing this client and going further however it becomes clear it actually is revision 10 as it says on the bottom right corner during loading.

**Comment by nonperforming** [comment]
I only updated `OpenSpadesPlus.cpp` and forgot to change the `PackageInfo.json`. Will be fixed soon
